name: dart_webcrypto
description: A wrapper of selected parts of the webcrypto API to dart
version: 0.0.1
author: Andreas Reiter <andreas.reiter@iaik.tugraz.at>
homepage: https://github.com/areiter/dart-webcrypto

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  crypto: '>=0.9.0 <1.0.0'
  browser_detect: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
